### ISSUE TITLE
When the data exists in *.json.gz format, the app is broken

### ISSUE THREAD

**Issue by joanise** [roedoejet/wordweaver#71]
On origin/main at the moment, commit 344b2f2000, the app is broken. I tracked it to the fact that the assets exist in compressed format. If you `rm projects/word-weaver/src/assets/data/fr/v1/*.json.gz`, then the app works again.

I have looked at `conjugation.service.ts` and I just can't see where you'd trigger decompressing the gzipped files, so I'm going to assign this to Aidan.

**Comment by roedoejet** [comment]
fixed by https://github.com/roedoejet/wordweaver/pull/74
